### ISSUE TITLE
Request: Update to PHP 7.3.15 please

### ISSUE THREAD

**Issue by sasansi** [iusrepo/php73#16]
Hello, I want to request all the PHP73 packages be updated to PHP 7.3.15:

https://www.php.net/archive/2020.php#2020-02-20-2

Thank you

**Comment by sasansi** [comment]
> 
> 
> Hello, I want to request all the PHP73 packages be updated to PHP 7.3.15:
> 
> https://www.php.net/archive/2020.php#2020-02-20-2
> 
> Thank you

NO need to bother to Update!!
I have changed my repo source and wont use IUS again
Thanks anyway

**Comment by carlwgeorge** [comment]
IUS is an open source project, not a product.  Threatening to not use something is not an effective way to convince volunteers to spend their time helping you.  Next time, consider sending a pull request like @chrisbarnett1 did.  He resolved this in https://github.com/iusrepo/php73/pull/17.
