### ISSUE TITLE
php73-imap

### ISSUE THREAD

**Issue by rossnick** [iusrepo/php73#2]
**What new package do you want?**

php73-imap

**Why?**

Latest stable for php7.3. Provides API for communicating with IMAP servers

**Testing**

I agree to test the new package to ensure that it works as expected. Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
We inherited these macros from the Fedora spec file.  We should be able to just flip `with_imap` to 1 (inside the `%else` of that `0%{?fedora}` conditional) to build this subpackage.  Would you like to contribute a pull request to do this?

**Comment by rossnick** [comment]
Sorray about that, With php72u, it was a separate package...
Yes I will. I'll try to do it this week.

**Comment by carlwgeorge** [comment]
Sure, it shows up to yum as a different package, but it comes from the same spec file (commonly referred to as a "subpackage").

https://github.com/iusrepo/php72u/blob/7.2.18-1/php72u.spec#L414-L429

At the time we forked php72u from Fedora, the conditionals to disable it on non-Fedora didn't exist, so php72u-imap was built without us making a conscious choice.

Sorry I wasn't clear at first.  When I said that this wouldn't be a new package, I meant in the context of the wishlist repo.  Enabling a subpackage is more of a feature change of the existing php73 package, hence why I moved this issue to this repo.

When you send the pull request, make sure to give yourself credit in the changelog.  #1 is an example of that you can follow.

**Comment by rossnick** [comment]
I realized it when I looked at the spec that it will build a separate package, but not a separate build. I've done the pull request...

**Comment by carlwgeorge** [comment]
Thanks for contributing to IUS!  I've published the new build in ius-testing, and I can see php73-imap available.  Please try it out and share your feedback.

**Comment by rossnick** [comment]
I haven't tested every single functions, but the previous code we have that runs in 7.2 function the same (connect, select maiblox, search, delete and expunge).
