### ISSUE TITLE
New version of oniguruma that was pushed to prod epel breaks php73-mbstring

### ISSUE THREAD

**Issue by rossnick** [iusrepo/php73#21]
Newer version of oniguruma now in epel (6.8.2-1) breaks php73-mbstring :

---> Package oniguruma.x86_64 0:5.9.5-3.el7 will be updated
--> Processing Dependency: libonig.so.2()(64bit) for package: php73-mbstring-7.3.10-1.el7.ius.x86_64
---> Package oniguruma.x86_64 0:6.8.2-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: php73-mbstring-7.3.10-1.el7.ius.x86_64 (@ius7-x86_64)
           Requires: libonig.so.2()(64bit)
           Removing: oniguruma-5.9.5-3.el7.x86_64 (@epel7-x86_64)
               libonig.so.2()(64bit)
           Updated By: oniguruma-6.8.2-1.el7.x86_64 (epel7-x86_64)
              ~libonig.so.5()(64bit)

For the time being I versionlocked oniguruma

**Comment by jeffsheltren** [comment]
Hi, you may have caught the window after EPEL pushed out oniguruma but before it was in the IUS repo (or maybe stale local yum cache?). This package was built with the new oniguruma and is now available in the IUS repo:

https://repo.ius.io/7/x86_64/packages/p/php73-mbstring-7.3.18-2.el7.ius.x86_64.rpm

If yum isn't seeing it, maybe try a `yum clean all` and then try the update again?

**Comment by rossnick** [comment]
You are perfectly right, we use spacewalk and repos aren't sync that often.

**Comment by yabdab** [comment]
I am still seeing this issue.

`Error: Package: php73-mbstring-7.3.18-2.el7.ius.x86_64 (ius)
           Requires: libonig.so.5()(64bit)`

I ran yum clean all, but it had no effect.

Is there anything else I can try to fix this?

Thanks.

**Comment by carlwgeorge** [comment]
@yabdab `libonig.so.5()(64bit)` is provided by `oniguruma-6.8.2-1.el7` from the EPEL repository.  On RHEL and CentOS, with the EPEL repository enabled, the php73-mbstring package works as expected.  Based on your oniguruma package, it appears you are using Amazon Linux.  Amazon Linux is loosely based on RHEL, but diverges significantly and cannot truly be considered a RHEL clone.  It's possible that adding the EPEL repository to your system will resolve this, but I can't be sure.  IUS does not claim to be compatible with Amazon Linux.  I've added an [FAQ item](https://ius.io/faq#is-ius-compatible-with-amazon-linux) about this to the website.
