### ISSUE TITLE
PHP 7.3.31 feedback

### ISSUE THREAD

**Issue by jdreese** [iusrepo/php73#35]
I just wanted to provide some feedback for 7.3.31 which is in testing. I upgraded to the following packages on one of my systems and haven't noticed any issues. Thanks.

php73-common-7.3.31-1.el7.ius.x86_64
php73-fpm-nginx-7.3.31-1.el7.ius.noarch
php73-fpm-7.3.31-1.el7.ius.x86_64
php73-mysqlnd-7.3.31-1.el7.ius.x86_64
php73-json-7.3.31-1.el7.ius.x86_64
php73-pdo-7.3.31-1.el7.ius.x86_64
php73-ldap-7.3.31-1.el7.ius.x86_64

**Comment by jeffsheltren** [comment]
Thanks for the feedback! I've pushed php73-7.3.31-1.el7.ius to IUS Stable.
