### ISSUE TITLE
php73-interbase

### ISSUE THREAD

**Issue by futureweb** [iusrepo/php73#4]
What new package do you want?
php73-interbase

Why?
Needed to access some DBs used by other Programs

I agree to test the new package to ensure that it works as expected. Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
Similar to [php73-imap](https://github.com/iusrepo/php73/issues/2), this wouldn't be a new package.  It's a [disabled subpackage](https://github.com/iusrepo/php73/blob/7.3.5-3/php73.spec#L524-L552) in the main php73 spec file, so I've transferred this issue to the correct repo.

We inherited these macros from the Fedora spec file. We should be able to just change `with_firebird` to 1 to build this subpackage. Would you like to contribute a pull request to do this?  It would look similar to #3.

**Comment by futureweb** [comment]
Hey @carlwgeorge,
never made a PR for PHP Package before - but let's give it a try! ;-) 
Like this?
https://github.com/iusrepo/php73/pull/5
Adjusting the intends to match properly ok?

**Comment by carlwgeorge** [comment]
Thanks for your contribution in #5.  The new build with php73-interbase has been published to ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).  Please try it out and share your feedback.

**Comment by carlwgeorge** [comment]
I need to get #6 released, so this change is getting published at the same time.

**Comment by futureweb** [comment]
@carlwgeorge - sorry for no testing yet - I'm out of Office this week - back next week.

**Comment by futureweb** [comment]
alright - looking good - working as expected! ;-)
